language: ruby
rvm:
- 2.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
branches:
  only:
  - develop
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: TSWAXbRWSGOkb+aqJQKF2HKBWRTJwskz+dRxfMNCBHo8nnWMEsC3o5JU2Ypbi79GMvOaSku68xJbV0n2z8qqk+8OTKdl1ckCGMbpjlT/VX1fTl8s4R/TXDKgXdOXoJ4j7K6nYILqjDLnCNtpc9dAWnz/FVlCtTIJkx6t9ozkJPA6vF18kmzgBdHBDPuhvNVg8exDc25NkH9ClpPCCajWY6mhfGiry0/JsCpRFOBUByAmRs5gx++hSOZafLnMGOd1szBpJLBku9FO+ckJ5XFgmO8GA8lNDZ+UlD1WvC58ao+pjxnKWkTcIqPFinLz1HEMly5LS5/fSQoNvmLyka460IkODMDmqgfB6EtUuds/GG/bMO2fSrIh3JBqYwB+nV9bgWcAwSIwJGBfEI7EgGb34uit/alaYdEPZ11/se271PZYZfTXFuEYoUAjy6i+uY7THiWhxBgEvuVPWnOdD1NmWQelahWo0Al8cq1ofWzviQYF2/vZ+yJt3wLTjUNh59Q/Uiz6w/P3kB+0TKCOezXrDNhHAhOBseJ29IhsITCMagRGz+Foeg5rkwZj4Nu+rYYkE6Zg02gTyueS4ci0iVBNfXx7aPgwdUSAq0S0AjoKQOflO2BfkG/YYyf4C4EMGFpqIl6WifcgfbmVljFCl5Nb7e3lTxSdkvFR80iW7kpguj4=
notifications:
  slack:
    secure: TET5NbblvZ0d3nTJyOzDSHZ3WUOCArpH8F64LSGZF/WQ87vqFbpyQSIqX7776fL4qYblPAc/hjOUtLH+hRzmHRVhKaZsLCCwcmL7/EHQe8jHt3lNrF8QWmwwFMs13oqmi+PAB3hpkX9Y4mKjyjLnjB0vqDnLMV4ktrnZ/GtM69i5hCIyaxKiYzp+uX7JOWop7JEtn9nDPT/IWzEYN2bxHw7G35BG8Ks0QK8LfSTcVruN2AJ1veFg1PbjE+kx6Brj37+4D3Pwn7mtcTmDAkygQtdCZFzaCzQTtY0PG3peKwp6lPQBJzmeo1IALydDvhuZ3CNgw7Vufazal0Bs476ip/w197EvgAtCOu1NWNQWAbl7DtnifXE/CnkPpkI5NeijpiVIulDe09aCh9LpwO+21CSG0kxIxWNJauK9tPPSYDBlZbB+V1A/kXXg+BLONbv5CfNRAN1azDRG71kxC68NKlfsPqPbp/IBZqa4J7X+jllPOw77k8qtwpj8me5+ctfzsl9Yi4Fyf9LQxpbdgmFCjyvefd7q6xRVSrj1zNZWWY4LhItfS9tdSHP7vNLFHhZ+mLQ4dpnSA9pHBC5LpYPYdcpJEL48tMn8QYXOGUIdpbZyrt/DfC1rYgeWKz33aWDLnxD89RK/eomRd7JPKihFPzDlDF2jFmKL2Oxd8TzMBPc=
